#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# COMMIT_MSG_FILE=$1

# ORIGINAL_COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
# echo "====commit-msg===="
# echo ORIGINAL_COMMIT_MSG: $ORIGINAL_COMMIT_MSG
