name: Release Drafter
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  foo_release_drafter:
    name: '[foo] Draft release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get release version
        id: generate-version
        uses: moonimooni/npm-monorepo-workflow/.github-action-composites/generate-calver@main
        with:
          directory: foo
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-foo.yml
          tag: ${{ steps.generate-version.outputs.version }}
          name: ${{ steps.generate-version.outputs.version }}
          version: ${{ steps.generate-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bar_release_drafter:
    name: '[bar] Draft release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get release version
        id: generate-version
        uses: moonimooni/npm-monorepo-workflow/.github-action-composites/generate-calver@main
        with:
          directory: bar
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-bar.yml
          tag: ${{ steps.generate-version.outputs.version }}
          name: ${{ steps.generate-version.outputs.version }}
          version: ${{ steps.generate-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
