name: run-modified-directories

on:
  push:
    branches:
      - 'main'

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          dir_names: 'true'

      - name: List all changed files
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
